apiVersion: apps/v1
kind: Deployment
metadata:
  name: provenance-deployment
  labels:
    app: node2
spec:
  selector:
    matchLabels:
      app: node2
  template:
    metadata:
      labels:
        app: node2
    spec:
      containers:
      - name: node
        env:
          - name: ID
            value: "2"
      volumes:
      - name: provenance-data
        persistentVolumeClaim:
          claimName: provenance-data-claim-node2
      - name: provenance-config
        persistentVolumeClaim:
          claimName: provenance-config-claim-node2