apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: provenance-data-claim-node2
  namespace: p8e
  labels:
    app: provenance-data-node2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}