apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: provenance-data-claim
  labels:
    app: provenance-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}