apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: provenance-config-claim
  labels:
    app: provenance-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}