apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-store-deployment
  namespace: p8e
  labels:
    app: object-store
spec:
  selector:
    matchLabels:
      app: object-store
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: object-store
    spec:
      containers:
      - name: object-store
        image: ghcr.io/provenance-io/object-store:0.1.0-public-release-beta.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: object-store
          mountPath: /mnt/data
        envFrom:
        - configMapRef:
            name: common-env
        - configMapRef:
            name: object-store-env
      volumes:
      - name: object-store
        persistentVolumeClaim:
          claimName: object-store-claim