apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: object-store-claim
  namespace: p8e
  labels:
    app: object-store
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}