apiVersion: v1
kind: Service
metadata:
  name: object-store
  namespace: p8e
  labels:
    app: object-store
spec:
  type: LoadBalancer
  selector:
    app: object-store
  ports:
    - protocol: TCP
      name: http
      port: 5000
      targetPort: 8080