apiVersion: v1
kind: Service
metadata:
  name: object-store
  labels:
    app: object-store
spec:
  type: LoadBalancer
  selector:
    app: object-store
  ports:
    - protocol: TCP
      name: object-store-http
      port: 5000
      targetPort: 8080