apiVersion: v1
kind: Secret
metadata:
  name: p8e-api
data:
  CHAINCODE_MNEMONIC: ZmFtZSBzaHVmZmxlIGhvbmV5IGdlbmVyYWwgdGVuIHZpcnR1YWwgY2xvdGggc3RvY2sgZXhjaGFuZ2UgbGlhciBtdWZmaW4gcGVybWl0IGJlaGluZCBtYXR0ZXIgZHVtYiBnZW51aW5lIHB1cmNoYXNlIGZveCB1c2VkIG9kb3IgZGVjbGluZSB0cnV0aCBsYWJlbCBsb2Fk # fame shuffle honey general ten virtual cloth stock exchange liar muffin permit behind matter dumb genuine purchase fox used odor decline truth label load