apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base
  - ./elasticsearch
  - ./p8e-postgres
  - ./provenance

patchesStrategicMerge:
  - ./p8e/p8e-secret.yaml
  - ./p8e/p8e-migration-secret.yaml
  - ./p8e-ui/p8e-ui-env.yaml