apiVersion: apps/v1
kind: Deployment
metadata:
  name: provenance-deployment
  labels:
    app: node3
spec:
  selector:
    matchLabels:
      app: node3
  template:
    metadata:
      labels:
        app: node3
    spec:
      containers:
      - name: node
        env:
          - name: ID
            value: "3"
      volumes:
      - name: provenance-data
        persistentVolumeClaim:
          claimName: provenance-data-claim-node3
      - name: provenance-config
        persistentVolumeClaim:
          claimName: provenance-config-claim-node3