apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: provenance-config-claim-node3
  namespace: p8e
  labels:
    app: provenance-config-node3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}