apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../dev

patchesStrategicMerge:
  - ./object-store/deployment.yaml
  - ./object-store/service.yaml
  - ./elasticsearch/deployment.yaml
  - ./elasticsearch/service.yaml
  - ./p8e-postgres/deployment.yaml
  - ./p8e-postgres/service.yaml