apiVersion: apps/v1
kind: Deployment
metadata:
  name: provenance-deployment
  labels:
    app: node0
spec:
  selector:
    matchLabels:
      app: node0
  template:
    metadata:
      labels:
        app: node0
    spec:
      containers:
      - name: node
        env:
          - name: ID
            value: "0"
      volumes:
      - name: provenance-data
        persistentVolumeClaim:
          claimName: provenance-data-claim-node0
      - name: provenance-config
        persistentVolumeClaim:
          claimName: provenance-config-claim-node0