apiVersion: v1
kind: ConfigMap
metadata:
  name: common
  namespace: p8e
data:
  DB_HOST: p8e-postgres
  DB_PORT: "5432"
  DB_USER: postgres
  ELASTICSEARCH_HOST: elasticsearch
  ELASTICSEARCH_PORT: "9200"
  ELASTICSEARCH_PREFIX: http
  ELASTICSEARCH_USERNAME: elastic
  POSTGRES_USER: postgres