apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
  namespace: p8e
  labels:
    app: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
        imagePullPolicy: Always
        ports:
        - containerPort: 9200
        volumeMounts:
        - name: elasticsearch
          mountPath: /usr/share/elasticsearch/data
        env:
          - name: ES_JAVA_OPTS
            value: -Xms512m -Xmx512m
          - name: bootstrap.memory_lock
            value: "true"
          - name: discovery.type
            value: single-node
          - name: http.cors.allow-credentials
            value: "true"
          - name: http.cors.allow-headers
            value: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
          - name: http.cors.allow-origin
            value: http://localhost:1358,http://127.0.0.1:1358
          - name: http.cors.enabled
            value: "true"
          - name: http.port
            value: "9200"
      volumes:
      - name: elasticsearch
        persistentVolumeClaim:
          claimName: elasticsearch-claim