apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-claim
  namespace: p8e
  labels:
    app: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}