apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: p8e
  labels:
    app: elasticsearch
spec:
  type: LoadBalancer
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      name: http
      port: 9200
      targetPort: 9200