apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: p8e-postgres-claim
  labels:
    app: p8e-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}