apiVersion: v1
kind: Service
metadata:
  name: p8e-webservice-service
  namespace: p8e
  labels:
    app: p8e-webservice
spec:
  type: LoadBalancer
  selector:
    app: p8e-webservice
  ports:
    - protocol: TCP
      name: http
      port: 5003
      targetPort: 8090