apiVersion: apps/v1
kind: Deployment
metadata:
  name: provenance-deployment
  labels:
    app: node1
spec:
  selector:
    matchLabels:
      app: node1
  template:
    metadata:
      labels:
        app: node1
    spec:
      containers:
      - name: node
        env:
          - name: ID
            value: "1"
      volumes:
      - name: provenance-data
        persistentVolumeClaim:
          claimName: provenance-data-claim-node1
      - name: provenance-config
        persistentVolumeClaim:
          claimName: provenance-config-claim-node1