apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: provenance-data-claim-node1
  labels:
    app: provenance-data-node1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}