apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: provenance-config-claim-node1
  labels:
    app: provenance-config-node1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}