apiVersion: apps/v1
kind: Deployment
metadata:
  name: p8e-migration-deployment
  namespace: p8e
  labels:
    app: p8e-migration
spec:
  selector:
    matchLabels:
      app: p8e-migration
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: p8e-migration
    spec:
      containers:
      - name: p8e-migration
        image: ghcr.io/provenance-io/p8e-migration:0.6.0-public-release-beta.5
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: common-env