apiVersion: v1
kind: Service
metadata:
  name: p8e-ui
  namespace: p8e
  labels:
    app: p8e-ui
spec:
  type: LoadBalancer
  selector:
    app: p8e-ui
  ports:
    - protocol: TCP
      name: p8e-ui-http
      port: 3000
      targetPort: 80